# Generated by Django 5.2.4 on 2025-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.IntegerField()),
                ('student_name', models.CharField(max_length=110)),
                ('arabic_degree', models.FloatField()),
                ('english_degree', models.FloatField()),
                ('science_degree', models.FloatField()),
                ('math_degree', models.FloatField()),
                ('art_degree', models.FloatField()),
                ('computer_degree', models.FloatField()),
                ('french_degree', models.FloatField()),
                ('english_level_degree', models.FloatField()),
                ('region_degree', models.FloatField()),
            ],
        ),
    ]
